version: '3.10'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  app:
    restart: always
    build:
      context: .
    volumes:
      - ./:/app
    command:
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    ports:
      - '8000:8000'
    depends_on:
      - postgres

  worker:
    restart: always
    build:
      context: .
    volumes:
      - ./:/app
    command: [ 'celery', '--workdir=.', '-A', 'sky', 'worker', '-l' ,'INFO' ]
    depends_on:
      - postgres
      - app
      - redis

  celery-beats:
    restart: always
    build:
      context: .
    volumes:
      - ./:/app
    command: [ 'celery','--workdir=.', '-A', 'sky', 'beat', '-l', 'INFO' ]
    depends_on:
      - postgres
      - app
      - redis
      - worker